# Generated by Django 2.1.4 on 2019-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollTrainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_details', models.CharField(default='', max_length=250)),
                ('course_date', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('private_address', models.CharField(default='', max_length=250)),
                ('office_address', models.CharField(default='', max_length=250)),
                ('date_of_birth', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('mobile_number', models.CharField(default='', max_length=20)),
                ('telephone_number', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('employer', models.CharField(default='', max_length=250)),
                ('job_title', models.CharField(default='', max_length=250)),
                ('length_of_employment', models.CharField(default='', max_length=10)),
                ('name_and_address_kin', models.CharField(default='', max_length=250)),
                ('relationship', models.CharField(default='', max_length=250)),
                ('contact_num', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('academic_qualifications', models.CharField(default='', max_length=250)),
                ('academic_qualification_insitute', models.CharField(default='', max_length=250)),
                ('academic_qualification_year', models.CharField(default='', max_length=10)),
                ('professional_qualifications', models.CharField(default='', max_length=250)),
                ('professional_qualification_insitute', models.CharField(default='', max_length=250)),
                ('professional_qualification_year', models.CharField(default='', max_length=10)),
                ('enrolled_on', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
