# Generated by Django 2.1.4 on 2019-01-15 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='visa_copy_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
