# Generated by Django 2.1.4 on 2019-01-16 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0002_auto_20190116_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_insitute',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualifications',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='contact_num',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='course_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='course_details',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='date_of_birth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='employer',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='enrolled_by',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='enrolled_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='job_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='length_of_employment',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='name_and_address_kin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='office_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='passport_copy',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='passport_size_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='private_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_insitute',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualifications',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='relationship',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='telephone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='visa_copy',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
