# Generated by Django 2.1.4 on 2019-01-21 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0003_auto_20190116_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_certificate_five',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_certificate_four',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_certificate_three',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_certificate_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_certificate_five',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_certificate_four',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_certificate_three',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_certificate_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
