# Generated by Django 2.1.4 on 2019-01-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0004_auto_20190121_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_insitute_five',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_insitute_four',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_insitute_three',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_insitute_two',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_year_five',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_year_four',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_year_three',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualification_year_two',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualifications_five',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualifications_four',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualifications_three',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='academic_qualifications_two',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_insitute_five',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_insitute_four',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_insitute_three',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_insitute_two',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_year_five',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_year_four',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_year_three',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualification_year_two',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualifications_five',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualifications_four',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualifications_three',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrolltrainee',
            name='professional_qualifications_two',
            field=models.CharField(default='', max_length=250),
        ),
    ]
