# Generated by Django 2.1.4 on 2019-01-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0006_enrolltrainee_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='approval',
            field=models.CharField(default='', max_length=50),
        ),
    ]
