# Generated by Django 2.1.4 on 2019-01-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0007_enrolltrainee_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolltrainee',
            name='approval',
            field=models.CharField(default='Approval Pending', max_length=50),
        ),
    ]
