# Generated by Django 2.1.4 on 2019-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0008_auto_20190127_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='approved_by',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
