# Generated by Django 2.1.4 on 2019-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0009_enrolltrainee_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolltrainee',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
