# Generated by Django 2.1.4 on 2019-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0010_enrolltrainee_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolltrainee',
            name='approved_by',
            field=models.CharField(default='', max_length=250),
        ),
    ]
