# Generated by Django 2.1.4 on 2019-01-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0011_auto_20190127_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_details', models.CharField(default='', max_length=250)),
                ('course_name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
