# Generated by Django 2.1.4 on 2019-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0014_subjectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='courses_list',
            field=models.CharField(default='', max_length=250),
        ),
    ]
