# Generated by Django 2.1.4 on 2019-01-29 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0015_classname_courses_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_subjects',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
