# Generated by Django 2.1.4 on 2019-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0016_course_course_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=250)),
                ('subject_type', models.CharField(default='', max_length=20)),
                ('subject_discription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectName',
        ),
    ]
