# Generated by Django 2.1.4 on 2018-12-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181218_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
    ]
