# Generated by Django 2.1.4 on 2018-12-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181218_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('department', models.CharField(default='', max_length=50)),
                ('job_title', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
