# Generated by Django 2.1.4 on 2018-12-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_setupuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupuserprofile',
            name='page_access',
            field=models.TextField(default=''),
        ),
    ]
