# Generated by Django 2.1.4 on 2018-12-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_setupuserprofile_page_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_list', models.TextField()),
            ],
        ),
    ]
