# Generated by Django 2.1.4 on 2018-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alldepartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupuserprofile',
            name='page_access',
            field=models.CharField(default='', max_length=100),
        ),
    ]
