# Generated by Django 2.1.4 on 2018-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181218_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
