# Generated by Django 2.1.4 on 2018-12-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pageaccess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetupUserProfile',
            new_name='SetupUserAccount',
        ),
    ]
