# Generated by Django 2.1.4 on 2018-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181219_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupuseraccount',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
