# Generated by Django 2.1.4 on 2018-12-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cns_mso',
            new_name='MsoCns',
        ),
    ]
