# Generated by Django 2.1.4 on 2018-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mso', '0002_auto_20181224_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msocns',
            name='supervisor_approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='msocns',
            name='tsm_approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
