# Generated by Django 2.1.4 on 2018-12-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mso', '0003_auto_20181224_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msocns',
            old_name='date_compleated',
            new_name='date_completed',
        ),
    ]
