# Generated by Django 2.1.4 on 2018-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mso', '0004_auto_20181224_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='msocns',
            name='posted_by_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
