# Generated by Django 2.1.4 on 2018-12-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mso', '0005_msocns_posted_by_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msocns',
            old_name='tsm_approval',
            new_name='manager_approval',
        ),
        migrations.RenameField(
            model_name='msocns',
            old_name='tsm_approval_date',
            new_name='manager_approval_date',
        ),
    ]
