# Generated by Django 2.1.4 on 2019-01-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogbookNames',
            new_name='LogbookName',
        ),
    ]
