# Generated by Django 2.1.4 on 2019-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20190105_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('posted_by', models.EmailField(default='', max_length=254)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
                ('logbook_name', models.CharField(default='', max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
