# Generated by Django 2.1.4 on 2019-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_newlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlog',
            name='posted_by_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
